### ISSUE TITLE
Please increase versionCode with each release

### ISSUE THREAD

**Issue by IzzySoft** [victorbnl/android-ip-scanner#1]
Currently, each of your APKs identifies as

    package: name='com.victorb.androidnetworkscanner' versionCode='1' versionName='1.0' compileSdkVersion='30' compileSdkVersionCodename='11'

because in `build.gradle` you're always sticking to

```yaml
        versionCode 1
        versionName "1.0"
```

That makes updates hard, as Android considers them all identical (it's using `versionCode` to tell which APK is "newer" – the one with the higher number). And hard to users to tell which version they have installed – they always see "1.0".

So may I suggest, going by your releases, to make the current version something like

```yaml
        versionCode 35
        versionName "1.3.5"
```

(feel free to use a different schema for `versionName` – that's just the "human readable" part and not technically relevant for anything else) – and then keep increasing with future releases? Thanks!

**Comment by marie-bnl** [comment]
Oh ok that seems boring to do manually but I guess there is no automatic way to do this x). I didn't know about this property, I'll increment it at each commit, thanks for your review!

**Comment by marie-bnl** [comment]
I guess it's solved, so I close the issue, feel free to open it again if you want to answer!

**Comment by IzzySoft** [comment]
Thanks! So all releases starting with "40" will increase up from 2 – so there's no relation between tag name and either versionName or versionCode? Best practise is to bind it to one of the two (most often the tag name is `v<versionName>`, second-most just `<versionName>`). That used consistently makes it quite easy to find out whether a newer version is available. Not strictly required, but very helpful.

**Comment by marie-bnl** [comment]
Well I didn't do that because I have a GitHub Action that makes a new release (so also a new tag) on each commit and builds the APK. I'll try to make the tags match the versionName! Thanks for your advises

**Comment by IzzySoft** [comment]
Thanks for picking them up – also in the name of your users :smile: And [take a look here](https://apt.izzysoft.de/fdroid/index/apk/com.victorb.androidnetworkscanner) in about 2.5h from now (updates are usually fetched within 24h of your tagging a release and attaching the APK to it). If you want a badge for that, you can [find it here](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it).

**Comment by marie-bnl** [comment]
OMG! Thanks a lot! Seems very useful! So it means each time there will be a new release, the APK will be available on the page? I'll add the badge!

**Comment by IzzySoft** [comment]
Yes – thanks to your fixing `build.gradle` :smiley: And people can use the [F-Droid](https://f-droid.org/) client to stay informed (my repo can be added there). If you can get tag names in sync with either `versionName` or `versionCode`, I could also help you get your app listed with the "main repo" (disclosure: I'm one of the maintainers there). If you want it, that is.

**Comment by marie-bnl** [comment]
Thank! I already thought about putting it on F-Droid but it seems a bit complicated. I'll try to think about a clean build system and add it when my app will be stable etc. Thanks for your help 😃

**Comment by IzzySoft** [comment]
Gladly! Just let me know when you want to start, and I gladly guide you through and help you there again.

**Comment by marie-bnl** [comment]
I made [a pre-commit hook](https://gist.github.com/Victor-Bo/cffc1a1b9e646faa5c790268ab3cf174) to increase the versionCode and name before each commit. Now I only have to make the release use the versionCode and that's it

**Comment by IzzySoft** [comment]
Cool! Do you tag a release on each commit? That explains your release frequency :smile: Quite unusual; this is only the 2nd project I see doing so. No prob, but my updater only picks one per day :laughing:

Btw, it's live now if you want to check. Thanks for adding the badge already!

PS: Oh, and you might wish to [check here](https://android.izzysoft.de/applists/category/named/network_admin_diagnosis#group_374). Now that your app is listed with my repo, I was able to add it to my app listings as well :smiley:

**Comment by marie-bnl** [comment]
xD I don't know if I'm doing good but you know I don't want to bother managing releases, like I just want to make my app, people to have always the latest source code and that's it 😂

For the fact you added it on your app list that's great but you must know that's it's in a VERY early stage, it must be full of bugs, I didn't even implement yet some things and it doesn't even detect my computer, I have no idea why XDD

**Comment by marie-bnl** [comment]
I finished the build system, now I have this structure

![Untitled Diagram(4)](https://user-images.githubusercontent.com/39555268/104853512-a8fe2780-5901-11eb-9a7a-1eaeb274a1ec.png)

**Comment by IzzySoft** [comment]
I've got something against your worries then: [merging this](https://github.com/Victor-Bo/android-network-scanner/pull/2) you can maintain what is shown as description for your app in my repo (and later, at F-Droid). You can also add screenshots, and more. I've linked you my "cheat sheet" which should make it easy to know what to place where. Some additional hints you can find [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane).

Nice diagram! To have not so excessive version "jumps", you could consider converting your pre-commit-hook into a pre-push-hook. What you don't push you won't release anyway. Just a thought, ignore if it doesn't fit :wink:

**Comment by marie-bnl** [comment]
Yes, completely true, thanks! I'll do that

I'll check your PR

**Comment by IzzySoft** [comment]
I've no idea what you're doing, Victor – but v1.3.0 again identifies with `versionCode 93`, while v1.1.0 had 1001000. So it won't ever be listed. Never decrease versionCode – I thought we had that fixed? This way we never get auto-update running :cry:

**Comment by marie-bnl** [comment]
Ok sorry, I think this time will be the last change but I'm not constant, I'm only starting in this domains and finding my way and I really change things often, I only give you more work. So I think the best would be to remove my app from your repository

**Comment by IzzySoft** [comment]
It's less my repo, Victor – but decreasing versionCode means users who had the previous version installed will never receive any updates anymore, and cannot even install them manually without uninstalling the app before (Android doesn't permit downgrades). So once you've increased to 1001000 (as you did with v1.1.0), you cannot go below that again without causing trouble. And versionCode 93 was already used with multiple versions btw.

Just let me know what your plans are concerning that, then I may see clearer what can be done. Until then I'll simply disable auto-updates for now, as they won't work anyway.

**Comment by marie-bnl** [comment]
If it would solve this I can start increasing from 1001000. Or we can delete 1001000 completely, depending on what you can do. This app was not meant to be used between the development, I think now it is. That means users are not supposed to have installed 1001000 before. I think I'll just start increasing from this number

**Comment by IzzySoft** [comment]
> If it would solve this I can start increasing from 1001000.

It would indeed. And it's a pattern I frequently encounter: `major x1000000 + minor x1000 + patch` per [semantic versioning](https://semver.org/). So the current v1.3.0 would be 1003000, per this pattern. But no problems should you decide to simply increase from that on by any number with each update.

Of course I could also simply remove v1.1.0 from my repo and you continue with "lower numbers". But that would mean folks who already had v1.1.0 installed will never get an update until they notice what was going on and manually uninstall+reinstall.

A third variant I've seen is using the date-of-release in the YYYYMMDD pattern (i.e. would you release today, versionCode would be 20210211). Might be OK, but then you'd be in trouble if for some reason you'll have to make a second release on the same day while already planning another one for tomorrow :wink:

I'd prefer the first variant, but it's of course your decision. Just let me know which you decided for – and if you stick to that, auto-update can be re-enabled.

**Comment by marie-bnl** [comment]
Ok so I'm on my phone so the next release will fix this, I can't do a release right now due to problems with apt-get but the source code is fixed, I'll use the first pattern, thanks for your help! This means you have nothing to remove because the version now in the source code is higher than all the ones I did

**Comment by IzzySoft** [comment]
Thanks a lot! And sure, no time pressure. If you just leave me a note here when the next version is available so I re-enable auto-update, that would be much appreciated.

**Comment by marie-bnl** [comment]
Version v1.3.1 published, the versionCode is fixed

**Comment by IzzySoft** [comment]
Confirmed, thanks! Auto-Update re-enabled.
