### ISSUE TITLE
Discussions about IzzyOnDroid

### ISSUE THREAD

**Issue by marie-bnl** [victorbnl/android-ip-scanner#3]
Hey @IzzySoft ! I think it's better to talk there as the previous issue has nothing to do with the discussion xD. 
First I had a question. In the fastlane folder I renamed "en-US" to "en" to make it general, is this a problem? And then what are the next steps to make it available on F-Droid?

**Comment by IzzySoft** [comment]
> In the fastlane folder I renamed "en-US" to "en" to make it general, is this a problem?

Yes, that is a problem. For some strange reason incomprehensible to all but proud US citizens (i.e. the majority of people, surprise!), this is the default and fallback for all non-existing things. So if I come with a `pl` locale and you offer no `pl`, the app would try presenting `en-US`. That not there either? OK, then no summary, no description, no screenshots etc.

> And then what are the next steps to make it available on F-Droid?

Opening a [Request for Packaging](https://gitlab.com/fdroid/rfp/issues). Details you can find in one of my articles [here](https://android.izzysoft.de/articles/named/fdroid-intro-2#rfp).

**Comment by marie-bnl** [comment]
Ok thanks! I renamed it again to en-US 😂. I guess the screenshots in en-US will be available for other locales as well? For example I'm french, if I visit this app on F-Droid, I'll see the descriptions in French and the screenshots from the english folder? And I put my screenshots in `fastlane\metadata\android\en-US\images\phoneScreenshots`, is it the correct folder? I saw this the source of others apps on F-Droid xD.

For the request for packaging I think I'll see that tomorrow, thanks!

**Comment by IzzySoft** [comment]
> I guess the screenshots in en-US will be available for other locales as well?

Fallback, as I said. Unless the other locales have more than 0 screenshots; there's no merging AFAIK.

> For the request for packaging I think I'll see that tomorrow, thanks!

Yupp, whenever you're ready!

**Comment by marie-bnl** [comment]
Thanks a lot, good night

**Comment by marie-bnl** [comment]
Can I modify the infos on IzzyOnDroid or must I ask you to modify it each time? Actually I want to modify the screenshots to use the ones in fastlane which I modified a bit

**Comment by IzzySoft** [comment]
Just go ahead! That's what Fastlane is for. All assets which are fastlane-enabled for your app will be fetched from Fastlane when a new release was fetched. Oh, that was the keyword: currently only shortdesc and fulldesc are enabled, as I could not yet evaluate what kind of screenshots you might provide and what handling they might need. Let me check… OK, done, enabled. Should be fetched then with your "Release 12" (did you get that stabilized now? Looked a bit weird last night with the "47" in between :laughing:). I try a manual fetch now with debug log to verify…

```
$ ./getRelease -p com.victorb.androidnetworkscanner -v
com.victorb.androidnetworkscanner: looking for 'https://api.github.com/repos/Victor-Bo/android-network-scanner/releases'
com.victorb.androidnetworkscanner: 2/12, GH https://github.com/Victor-Bo/android-network-scanner/releases: https://github.com/Victor-Bo/android-network-scanner/releases/download/12/android-network-scanner.apk
- Grabbing update for com.victorb.androidnetworkscanner: OK
- Checking '/web/ftp/repo/fdroid/repo/com.victorb.androidnetworkscanner_12.apk' for libraries and malware …
com.victorb.androidnetworkscanner: calling 'getFastlaneMeta(github,[host:github.com,owner:Victor-Bo,repo:android-network-scanner,path:/fastlane/metadata/android])'
com.victorb.androidnetworkscanner: FastlaneFeatures shortdesc,fulldescMD,screenshotsJPG
com.victorb.androidnetworkscanner: looking for 'https://api.github.com/repos/Victor-Bo/android-network-scanner/contents/fastlane%2Fmetadata%2Fandroid'
com.victorb.androidnetworkscanner: looking for 'https://api.github.com/repos/Victor-Bo/android-network-scanner/contents/fastlane%2Fmetadata%2Fandroid%2Fde'
com.victorb.androidnetworkscanner: looking for 'https://api.github.com/repos/Victor-Bo/android-network-scanner/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US'
com.victorb.androidnetworkscanner: looking for 'https://api.github.com/repos/Victor-Bo/android-network-scanner/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages'
com.victorb.androidnetworkscanner: looking for 'https://api.github.com/repos/Victor-Bo/android-network-scanner/contents/fastlane%2Fmetadata%2Fandroid%2Fen-US%2Fimages%2FphoneScreenshots'
com.victorb.androidnetworkscanner: looking for 'https://api.github.com/repos/Victor-Bo/android-network-scanner/contents/fastlane%2Fmetadata%2Fandroid%2Ffi'
com.victorb.androidnetworkscanner: looking for 'https://api.github.com/repos/Victor-Bo/android-network-scanner/contents/fastlane%2Fmetadata%2Fandroid%2Ffr'
com.victorb.androidnetworkscanner: looking for 'https://api.github.com/repos/Victor-Bo/android-network-scanner/contents/fastlane%2Fmetadata%2Fandroid%2Fit'
com.victorb.androidnetworkscanner: checking locale 'de'
com.victorb.androidnetworkscanner: updating '/web/ftp/repo/fdroid/metadata/com.victorb.androidnetworkscanner/de/short_description.txt'
com.victorb.androidnetworkscanner: checking locale 'en-US'
com.victorb.androidnetworkscanner: replacing '/web/ftp/repo/fdroid/metadata/com.victorb.androidnetworkscanner/en-US/full_description.txt' with fromMD
com.victorb.androidnetworkscanner: updating '/web/ftp/repo/fdroid/metadata/com.victorb.androidnetworkscanner/en-US/short_description.txt'
com.victorb.androidnetworkscanner: updating '/web/ftp/repo/fdroid/repo/com.victorb.androidnetworkscanner/en-US/phoneScreenshots/1.png' as JPG
com.victorb.androidnetworkscanner: updating '/web/ftp/repo/fdroid/repo/com.victorb.androidnetworkscanner/en-US/phoneScreenshots/2.png' as JPG
com.victorb.androidnetworkscanner: cross-checking for obsolete screenshots
com.victorb.androidnetworkscanner: screenshots in Fastlane: 1,2
com.victorb.androidnetworkscanner: removing /web/ftp/repo/fdroid/repo/com.victorb.androidnetworkscanner/en-US/phoneScreenshots/screen_dark.jpg
com.victorb.androidnetworkscanner: removing /web/ftp/repo/fdroid/repo/com.victorb.androidnetworkscanner/en-US/phoneScreenshots/screen_light.jpg
com.victorb.androidnetworkscanner: local screenshots checked: 1,2,screen_dark,screen_light
com.victorb.androidnetworkscanner: checking locale 'fi'
com.victorb.androidnetworkscanner: updating '/web/ftp/repo/fdroid/metadata/com.victorb.androidnetworkscanner/fi/short_description.txt'
com.victorb.androidnetworkscanner: checking locale 'fr'
com.victorb.androidnetworkscanner: replacing '/web/ftp/repo/fdroid/metadata/com.victorb.androidnetworkscanner/fr/full_description.txt' with fromMD
com.victorb.androidnetworkscanner: updating '/web/ftp/repo/fdroid/metadata/com.victorb.androidnetworkscanner/fr/short_description.txt'
com.victorb.androidnetworkscanner: checking locale 'it'
com.victorb.androidnetworkscanner: replacing '/web/ftp/repo/fdroid/metadata/com.victorb.androidnetworkscanner/it/full_description.txt' with fromMD
com.victorb.androidnetworkscanner: updating '/web/ftp/repo/fdroid/metadata/com.victorb.androidnetworkscanner/it/short_description.txt'
```

Looks good! Updated fine from 2→12 ("2/12" means "oldVersionName/newVersionName" in that log). Check results for yourself in about half an hour (when the sync is through).

**Comment by IzzySoft** [comment]
PS: Wow, you cut the APK size in half! From 3.2M to just 1.4M. Congrats!

**Comment by marie-bnl** [comment]
How did I do this O.O I didn't even notice it XD maybe because I used more files before and I now have nearly all in one ugly function. I removed the progress bar too, to make the refresh button rotate instead. For the release 47 it's a remaining release from the old build system 😂

**Comment by marie-bnl** [comment]
Removed release and tag 47

**Comment by marie-bnl** [comment]
Btw I wanted to ask, when you say you fetch releases each day, I guess it's the latest one ?

For example if in a day I make these releases :
- Release 1
- Release 2
- Release 3

I guess it will take directly the third release? 
Or a day the first, another the second and then the third and take three days to get the latest?

**Comment by IzzySoft** [comment]
It's only considering the latest tag that has an APK attached. So in your example, it would only fetch "Release 3" and ignore 1+2. Else it would never catch up with yours :rofl:

**Comment by marie-bnl** [comment]
Yes that's why I asked XDDD thanks 😂

**Comment by marie-bnl** [comment]
Oh also does IzzyOnDroid support .aab app bundles?

**Comment by IzzySoft** [comment]
No, it doesn't. Only APKs.

**Comment by marie-bnl** [comment]
Ok thanks 👍

**Comment by goyalyashpal** [comment]
> For some strange reason incomprehensible to all but proud US citizens...

lolll, soooo aptly said. it's really incomprehensible to me too.

**Comment by marie-bnl** [comment]
I guess it was easier to code
